### ISSUE TITLE
Wrong content type application/xml instead of application/json

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/http-proxy#59] opened 2022-02-11 09:57 UTC
In particular the problem is that the `Accept` header is not forwarded correctly: 
Sample request: 

```
curl --location --request POST 'https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fwps%3Fservice%3DWPS%26version%3D1.0.0%26REQUEST%3DExecute' \
--header 'Connection: keep-alive' \
--header 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Content-Type: application/xml' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36' \
--header 'sec-ch-ua-platform: "Linux"' \
--header 'Origin: http://localhost:8081' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Referer: http://localhost:8081/' \
--header 'Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7' \
--data-raw '<?xml version="1.0" encoding="UTF-8"?><wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:dwn="http://geoserver.org/wps/download" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd"><ows:Identifier>gs:Aggregate</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType="text/xml" xlink:href="http://geoserver/wfs" method="POST"><wps:Body><wfs:GetFeature  outputFormat="GML2" service="WFS" version="1.0.0"><wfs:Query typeName="gs:us_states"></wfs:Query></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>aggregationAttribute</ows:Identifier><wps:Data><wps:LiteralData>STATE_ABBR</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>function</ows:Identifier><wps:Data><wps:LiteralData>Count</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>singlePass</ows:Identifier><wps:Data><wps:LiteralData>false</wps:LiteralData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType="application/json"><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>'
```
Returns : `Content-Type: application/xml` but the content of the response is in JSON format

The direct request
```
curl --location --request POST 'https://gs-stable.geo-solutions.it/geoserver/wps?service=WPS&version=1.0.0&REQUEST=Execute' \
--header 'Connection: keep-alive' \
--header 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Content-Type: application/xml' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36' \
--header 'sec-ch-ua-platform: "Linux"' \
--header 'Origin: http://localhost:8081' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Referer: http://localhost:8081/' \
--header 'Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7' \
--data-raw '<?xml version="1.0" encoding="UTF-8"?><wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:dwn="http://geoserver.org/wps/download" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd"><ows:Identifier>gs:Aggregate</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType="text/xml" xlink:href="http://geoserver/wfs" method="POST"><wps:Body><wfs:GetFeature  outputFormat="GML2" service="WFS" version="1.0.0"><wfs:Query typeName="gs:us_states"></wfs:Query></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>aggregationAttribute</ows:Identifier><wps:Data><wps:LiteralData>STATE_ABBR</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>function</ows:Identifier><wps:Data><wps:LiteralData>Count</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>singlePass</ows:Identifier><wps:Data><wps:LiteralData>false</wps:LiteralData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType="application/json"><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>'
```

Returns : `Content-Type: application/json` the correct one.

**Comment by nmco** [comment] 2022-02-12 14:23
@shadab-geo let's follow the usual workflow, and perform the initial assessment boxed to two hours maximum.

**Comment by nmco** [comment] 2022-02-12 14:35
On a second thought since you are quite busy @shadab-geo, @ydeliorman can you have a look at this one?

**Comment by tdipisa** [comment] 2022-02-14 09:44
It seems to me it probably depends on latest http-proxy updates performed by @shadab-geo.

Performing the request to MS DEV passing through the proxy (v1.2-SNAPSHOT) we have _Content-Type: application/xml_ in response Headers:

```
curl 'https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fwps%3Fservice%3DWPS%26version%3D1.0.0%26REQUEST%3DExecute%26ms2-authkey%3Df5b9e2bf-d5c8-45ac-8a22-dd85932f560d' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36' \
  -H 'Content-Type: application/xml' \
  -H 'Origin: https://dev-mapstore.geosolutionsgroup.com' \
  -H 'Referer: https://dev-mapstore.geosolutionsgroup.com/mapstore/' \
  -H 'Accept-Language: en,it;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6' \
  -H 'Cookie: _gcl_au=1.1.1799171789.1639741068; _ga=GA1.2.1536343127.1639741068' \
  --data-raw '<?xml version="1.0" encoding="UTF-8"?><wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:dwn="http://geoserver.org/wps/download" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd"><ows:Identifier>gs:Aggregate</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType="text/xml" xlink:href="http://geoserver/wfs" method="POST"><wps:Body><wfs:GetFeature  outputFormat="GML2" service="WFS" version="1.0.0"><wfs:Query typeName="gs:us_states"><ogc:Filter><ogc:And><ogc:Intersects><ogc:PropertyName>the_geom</ogc:PropertyName><gml:Polygon srsName="EPSG:3857"><gml:exterior><gml:LinearRing><gml:posList>-11114555.40889091 5033836.934748568 -11114555.40889091 5836119.983629778 -11858134.820049105 5836119.983629778 -11858134.820049105 5033836.934748568 -11114555.40889091 5033836.934748568</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></ogc:Intersects><ogc:Intersects><ogc:PropertyName>the_geom</ogc:PropertyName><gml:Polygon srsName="EPSG:3857"><gml:exterior><gml:LinearRing><gml:posList>-15987681.209931165 2317914.034685443 -15987681.209931165 6764714.59220386 -6595099.174248706 6764714.59220386 -6595099.174248706 2317914.034685443 -15987681.209931165 2317914.034685443</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></ogc:Intersects></ogc:And></ogc:Filter></wfs:Query></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>aggregationAttribute</ows:Identifier><wps:Data><wps:LiteralData>LAND_KM</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>function</ows:Identifier><wps:Data><wps:LiteralData>Sum</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>singlePass</ows:Identifier><wps:Data><wps:LiteralData>false</wps:LiteralData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType="application/json"><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>' \
  --compressed \
```

While performing the request to MS QA passing through the proxy (v1.1.1) we have _Content-Type: application/json_ in response Headers:

```
curl 'https://qa-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fwps%3Fservice%3DWPS%26version%3D1.0.0%26REQUEST%3DExecute%26ms2-authkey%3Df5b9e2bf-d5c8-45ac-8a22-dd85932f560d' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36' \
  -H 'Content-Type: application/xml' \
  -H 'Origin: https://qa-mapstore.geosolutionsgroup.com' \
  -H 'Referer: https://qa-mapstore.geosolutionsgroup.com/mapstore/' \
  -H 'Accept-Language: en,it;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6' \
  -H 'Cookie: _gcl_au=1.1.1799171789.1639741068; _ga=GA1.2.1536343127.1639741068' \
  --data-raw '<?xml version="1.0" encoding="UTF-8"?><wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:dwn="http://geoserver.org/wps/download" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd"><ows:Identifier>gs:Aggregate</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType="text/xml" xlink:href="http://geoserver/wfs" method="POST"><wps:Body><wfs:GetFeature  outputFormat="GML2" service="WFS" version="1.0.0"><wfs:Query typeName="gs:us_states"><ogc:Filter><ogc:And><ogc:Intersects><ogc:PropertyName>the_geom</ogc:PropertyName><gml:Polygon srsName="EPSG:3857"><gml:exterior><gml:LinearRing><gml:posList>-11114555.40889091 5033836.934748568 -11114555.40889091 5836119.983629778 -11858134.820049105 5836119.983629778 -11858134.820049105 5033836.934748568 -11114555.40889091 5033836.934748568</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></ogc:Intersects><ogc:Intersects><ogc:PropertyName>the_geom</ogc:PropertyName><gml:Polygon srsName="EPSG:3857"><gml:exterior><gml:LinearRing><gml:posList>-15987681.209931165 2317914.034685443 -15987681.209931165 6764714.59220386 -6595099.174248706 6764714.59220386 -6595099.174248706 2317914.034685443 -15987681.209931165 2317914.034685443</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></ogc:Intersects></ogc:And></ogc:Filter></wfs:Query></wfs:GetFeature></wps:Body></wps:Reference></wps:Input><wps:Input><ows:Identifier>aggregationAttribute</ows:Identifier><wps:Data><wps:LiteralData>LAND_KM</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>function</ows:Identifier><wps:Data><wps:LiteralData>Sum</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>singlePass</ows:Identifier><wps:Data><wps:LiteralData>false</wps:LiteralData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput mimeType="application/json"><ows:Identifier>result</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>' \
  --compressed \
```

**Comment by offtherailz** [comment] 2022-02-14 09:50
I notify also this, giving bad request:

https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities

While previous version works well: 
https://qa-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities

**Comment by tdipisa** [comment] 2022-02-14 09:58
> I notify also this, giving bad request:
> 
> https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities
> 
> While previous version works well: https://qa-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeorchestra.geo-solutions.it%2Fgeoserver%2Fwms%3Fservice%3DWMS%26version%3D1.3.0%26request%3DGetCapabilities

@offtherailz I've already opened a dedicate issue on MS for this:
https://github.com/geosolutions-it/MapStore2/issues/7862

**Comment by nmco** [comment] 2022-02-14 10:19
@ydeliorman is investigating this one.

**Comment by nmco** [comment] 2022-02-14 16:55
In GeoServer classic OGC services (WPS, WMS, WFS, ...) don' care about the requests headers, but they need to set the right response headers.

**In this case, the issue is not the content which is JSON as expected, it's that the ``Content-type`` header for the response is wrong, can you check this @ydeliorman.**

**Comment by ydeliorman** [comment] 2022-02-15 05:30
working on this

**Comment by ydeliorman** [comment] 2022-02-15 08:04
@nmco 

- Requests that send to dev server which uses http-proxy 1.2-SNAPSHOT, return Content-type header for the response correctly. It changes when we switch to application/json from application/xml.
- If we send the same request to the stable server which uses http-proxy 1.1-SNAPSHOT, returns an incorrect Content-type header for the response.

We can deduce from the top, _geoserver wps request returns an incorrect content-type header in the result and http-proxy 1.2 fixes it_. I will investigate;

1. Make a WPS request with content-type from my local and see if the response returns correctly.
2. Make the same WPS request using http-proxy 1.1 and 1.2 snapshots.

**Comment by aaime** [comment] 2022-02-15 10:36
For the first issue, go and enable entity resolution in the global settings (it's an issue that would not happen running from the jars, but shows up when running from the sources, don't worry about it):

![image](https://user-images.githubusercontent.com/325433/154044832-74c29447-8504-41ab-966f-a69c2598335f.png)

**Comment by shadab-geo** [comment] 2022-02-15 10:55
regarding the second issue:
you need to whitelist the GeoServer path.
If you are running a local http-proxy server using jetty server (i.e. via start class under test package).
You can update the below property in the file src/test/resources/proxy.properties file as below. 
```reqtypeWhitelist.geostore = (.*geostore.*)|(.*geoserver.*)```
This will allow both the paths i.e. geoserver as well as geostore.

**Comment by ydeliorman** [comment] 2022-02-15 11:22
@nmco 
@aaime @shadab-geo thank you very much for unblocking. We have multiple scenarios in terms of response's header content-type

1. When a WPS request is done to the GeoServer without http-proxy, the response's content-type is different from the requests' content-type. Not expected behavior.
2. When a WPS request is done to the GeoServer using 1.2 http-proxy, the response's content-type is the same with requests' content-type.  Expected behavior.
3. When a WPS request is done to the GeoServer using 1.1 http-proxy, the response's content-type is different from the requests' content-type. Not expected behavior.

We can say that 1.2 http-proxy is running correctly in terms of having the same content-type both in request and response. WPS request from GeoServer without proxy and WPS request using 1.1 http-proxy have different content-type in request and response headers.

**Comment by nmco** [comment] 2022-02-15 12:27
We clarified the issue with @ydeliorman he will get back with more feedback today.

**Comment by ydeliorman** [comment] 2022-02-17 16:54
@nmco 

We had a look with @taba90 to the error and managed to solve it. The problem is with the old library that is being used in the 1.1 version, response and requests headers are handled in a different way. The solve the issue we need to change [here](https://github.com/geosolutions-it/http-proxy/blob/master/src/main/java/it/geosolutions/httpproxy/HTTPProxy.java#L754) 
`httpMethodProxyRequest.getAllHeaders()` to
`response.getAllHeaders()`

@tdipisa @offtherailz In the 1.1 version when we set `<wps:RawDataOutput mimeType="application/xml">` response body's Content-Type returns text/xml. It will be the same case when we do the fix in 1.2 version. Is that suitable for your case?

The plan:
changing the code, some manual tests, and writing a unit test will take 4 hours.

**Comment by nmco** [comment] 2022-02-17 17:09
Go ahead @ydeliorman, we need to close this.

**Comment by tdipisa** [comment] 2022-02-21 15:44
Thank you @ydeliorman.
@taba90 can you review the PR please and let me know?

**Comment by ydeliorman** [comment] 2022-02-22 10:39
@nmco PR is merged. Do we need any backporting?

**Comment by tdipisa** [comment] 2022-02-22 10:54
Please wait @ydeliorman. Let's test it before. @ydeliorman @taba90 please let me know if the MVN repo is updated with these latest changes provided on master.

**Comment by tdipisa** [comment] 2022-02-22 13:49
@offtherailz the MVN repo is aligned with latest changes provided on http-proxy master branch. Can you please do a quick check by using 1.3-SNAPSHOT as a new dependency version for http-proxy?

**Comment by offtherailz** [comment] 2022-02-22 14:23
I took a look at the solutions, it seems rational. 
I checked and it is deployed for 1.3-SNAPSHOT (build server geo-solutions.it builds master) and so present on maven.geo-solutions.it
I tested the CURL request that was failing and now it works. 

LGTM

**Comment by tdipisa** [comment] 2022-03-07 14:04
Tested in c027 client environment with both 1.3-SNAPSHOT and 1.2-SNAPSHOT It is working now.

**Closed** 2022-11-04 09:41 UTC
Labels: bug, Priority: High, C070-NPA-CGG-2021-DEV
